on: [push, pull_request]

name: CI

jobs:
  build:
    name: Compile and Build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '10.0'
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Cargo Make
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1
        
        with:
          java-version: 1.8

      - name: Setup Android SDK 
        
        uses: android-actions/setup-android@v2

      - name: Cache NDK 
        
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: /home/runner/android/ndk-bundle
          key: ${{ runner.os }}-ndk

      - name: Install Android NDK 
        if: steps.cache-ndk.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-latest'
        run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager ndk-bundle

      - name: Set Android NDK Env 
        run: echo 'name=ANDROID_NDK_HOME::/home/runner/android/ndk-bundle' >> $GITHUB_ENV

      - name: Install Android Targets 
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Run cargo make android
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android

      - name: Build APK (Fat, Debug)
        run: flutter build apk --debug --no-sound-null-safety
      - name: Save APK (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: flab-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Build APK (Slow, Release)
        run: cargo make clean && cargo make --profile release android && flutter build apk --release
      - name: Save APK (Release)
        uses: actions/upload-artifact@v2
        with:
          name: flab-release
          path: build/app/outputs/flutter-apk/app-release.apk